modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/MaxSaleh/Dynamic-Vehicles/issues"
license="All rights reserved"

[[mods]]
    modId="dynamicvehicles"
    version="${file.jarVersion}"
    displayName="Dynamic Vehicles"
    logoFile=""
    credits=""
    authors="MaxIsH0t"
    description="This is a brand new vehicle mod for the newer minecraft versions!"

[[dependencies.dynamicvehicles]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dynamicvehicles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
